twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        site_name: 'CS Coaching'

when@test:
    twig:
        strict_variables: true
